- name: Stop MySQL and create migration
  hosts: localhost
  become: yes
  tasks:
    - name: Dump new data to a SQL file
      shell: mysqldump -u root -p'Software@2025' --socket=/var/run/mysqld/mysqld.sock subscribers_db > /tmp/subscribers_backup.sql
      register: dump_result
      changed_when: false

    - name: Show dump output (for debugging)
      debug:
        var: dump_result

    - name: Stop MySQL service
      service:
        name: mysql
        state: stopped

    - name: Archive the backup file
      command: mv /tmp/subscribers_backup.sql ~/subscribers_migration.sql
